
export const FETCH_TEMPLATES = "FETCH_TEMPLATES";

export const SET_CATEGORY = "SET_CATEGORY";
export const SORT_BY_CATEGORY = "SORT_BY_CATEGORY";

export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";

export const SORT_BY_SEARCH = "SORT_BY_SEARCH";
export const SORT_BY_ORDER_ASCENDING = "SORT_BY_ORDER_ASCENDING";
export const SORT_BY_ORDER_DESENDING = "SORT_BY_ORDER_DESENDING";
export const SORT_BY_DATE_ASCENDING = "SORT_BY_DATE_ASCENDING";
export const SORT_BY_DATE_DESENDING = "SORT_BY_DATE_DESENDING";
export const SORT_BY_DEFAULT = "SORT_BY_DEFAULT";

